project: VLMEvalKit

default_partition: kill-shared

modules:
  python: lang/Python/3.11.5-GCCcore-13.2.0

env_watch:
  - scripts/setup_env.sh
  - requirements.txt
  - requirements.lock
  - requirements-dev.txt
  - pyproject.toml
  - poetry.lock
  - uv.lock
  - environment.yml

# Add snapshot_excludes if you want to skip directories during submissions
snapshot_excludes:
  - .github
  - .git
  - assets
  - docker
  - docs
  - .venv